import type { Confidence, Evidence, Fragrance, MetricEstimate } from "../domain/types.ts";

function evidence(sourceId: string, confidence: Confidence = "high", sampleSize = 120): Evidence {
  return {
    sourceId,
    kind: sourceId === "community" ? "community" : "curated",
    confidence,
    license: "CC0-1.0",
    sampleSize,
  };
}

function metric(value: number, confidence: Confidence = "high", sampleSize = 120): MetricEstimate {
  return { value, confidence, sampleSize, evidence: [evidence("community", confidence, sampleSize)] };
}

export const FIXTURE_FRAGRANCES: readonly Fragrance[] = [
  {
    id: "brisa-vetiver",
    name: "Brisa Vetiver",
    brand: "Casa Aurora",
    family: "cítrico amadeirado",
    segments: ["brasileiro", "acessível"],
    concentrations: ["eau de parfum"],
    topNotes: ["bergamota", "limão"],
    heartNotes: ["chá verde", "lavanda"],
    baseNotes: ["vetiver", "cedro"],
    accords: [
      { id: "cítrico", weight: 0.95 },
      { id: "amadeirado", weight: 0.78 },
      { id: "verde", weight: 0.66 },
    ],
    occasions: [
      { id: "escritório", weight: 0.95 },
      { id: "casual", weight: 0.82 },
      { id: "encontro", weight: 0.58 },
    ],
    formality: 0.58,
    performance: {
      longevity: { minimumHours: 5, maximumHours: 8, confidence: "high", sampleSize: 180 },
      projection: metric(0.45, "high", 180),
      sillage: metric(0.42, "high", 170),
    },
    climate: {
      idealTemperatureMinC: 20,
      idealTemperatureMaxC: 33,
      idealHumidity: 0.68,
      indoorFit: 0.92,
      outdoorFit: 0.8,
    },
    priceTier: 2,
    dataConfidence: "high",
    evidence: [evidence("curadoria")],
  },
  {
    id: "brisa-vetiver-intense",
    name: "Brisa Vetiver Intense",
    brand: "Casa Aurora",
    family: "cítrico amadeirado",
    segments: ["brasileiro", "acessível"],
    concentrations: ["parfum"],
    topNotes: ["bergamota", "limão"],
    heartNotes: ["chá verde", "lavanda"],
    baseNotes: ["vetiver", "cedro", "âmbar"],
    accords: [
      { id: "cítrico", weight: 0.82 },
      { id: "amadeirado", weight: 0.9 },
      { id: "verde", weight: 0.55 },
    ],
    occasions: [
      { id: "escritório", weight: 0.78 },
      { id: "encontro", weight: 0.7 },
    ],
    formality: 0.68,
    performance: {
      longevity: { minimumHours: 8, maximumHours: 11, confidence: "medium", sampleSize: 55 },
      projection: metric(0.68, "medium", 55),
      sillage: metric(0.65, "medium", 49),
    },
    climate: {
      idealTemperatureMinC: 14,
      idealTemperatureMaxC: 27,
      idealHumidity: 0.5,
      indoorFit: 0.68,
      outdoorFit: 0.85,
    },
    priceTier: 3,
    dataConfidence: "medium",
    evidence: [evidence("curadoria", "medium", 55)],
  },
  {
    id: "cha-de-iris",
    name: "Chá de Íris",
    brand: "Ateliê Prisma",
    family: "floral almiscarado",
    segments: ["nicho", "brasileiro"],
    concentrations: ["eau de parfum"],
    topNotes: ["mandarina", "folha de violeta"],
    heartNotes: ["íris", "chá preto"],
    baseNotes: ["almíscar", "sândalo"],
    accords: [
      { id: "atalcado", weight: 0.88 },
      { id: "floral", weight: 0.72 },
      { id: "almiscarado", weight: 0.65 },
    ],
    occasions: [
      { id: "escritório", weight: 0.9 },
      { id: "formal", weight: 0.78 },
      { id: "encontro", weight: 0.7 },
    ],
    formality: 0.8,
    performance: {
      longevity: { minimumHours: 6, maximumHours: 9, confidence: "medium", sampleSize: 68 },
      projection: metric(0.34, "medium", 68),
      sillage: metric(0.32, "medium", 61),
    },
    climate: {
      idealTemperatureMinC: 15,
      idealTemperatureMaxC: 28,
      idealHumidity: 0.45,
      indoorFit: 0.96,
      outdoorFit: 0.55,
    },
    priceTier: 4,
    dataConfidence: "medium",
    evidence: [evidence("curadoria", "medium", 68)],
  },
  {
    id: "horizonte-azul",
    name: "Horizonte Azul",
    brand: "Mar Aberto",
    family: "aquático aromático",
    segments: ["designer", "acessível"],
    concentrations: ["eau de toilette"],
    topNotes: ["toranja", "notas marinhas"],
    heartNotes: ["sálvia", "alecrim"],
    baseNotes: ["madeiras claras", "almíscar"],
    accords: [
      { id: "aquático", weight: 0.95 },
      { id: "aromático", weight: 0.72 },
      { id: "cítrico", weight: 0.6 },
    ],
    occasions: [
      { id: "casual", weight: 0.95 },
      { id: "escritório", weight: 0.72 },
      { id: "esporte", weight: 0.84 },
    ],
    formality: 0.35,
    performance: {
      longevity: { minimumHours: 3, maximumHours: 6, confidence: "high", sampleSize: 220 },
      projection: metric(0.5, "high", 220),
      sillage: metric(0.48, "high", 205),
    },
    climate: {
      idealTemperatureMinC: 23,
      idealTemperatureMaxC: 38,
      idealHumidity: 0.8,
      indoorFit: 0.75,
      outdoorFit: 0.94,
    },
    priceTier: 1,
    dataConfidence: "high",
    evidence: [evidence("curadoria")],
  },
  {
    id: "ambar-noturno",
    name: "Âmbar Noturno",
    brand: "Maison Obscura",
    family: "âmbar gourmand",
    segments: ["nicho", "luxo"],
    concentrations: ["extrait de parfum"],
    topNotes: ["canela", "açafrão"],
    heartNotes: ["baunilha", "rosa"],
    baseNotes: ["oud", "âmbar", "incenso"],
    accords: [
      { id: "ambarado", weight: 0.98 },
      { id: "doce", weight: 0.9 },
      { id: "especiado", weight: 0.76 },
    ],
    occasions: [
      { id: "festa", weight: 0.92 },
      { id: "encontro", weight: 0.9 },
      { id: "escritório", weight: 0.18 },
    ],
    formality: 0.82,
    performance: {
      longevity: { minimumHours: 10, maximumHours: 16, confidence: "high", sampleSize: 410 },
      projection: metric(0.96, "high", 410),
      sillage: metric(0.94, "high", 388),
    },
    climate: {
      idealTemperatureMinC: 5,
      idealTemperatureMaxC: 20,
      idealHumidity: 0.28,
      indoorFit: 0.35,
      outdoorFit: 0.82,
    },
    priceTier: 5,
    dataConfidence: "high",
    evidence: [evidence("curadoria")],
  },
  {
    id: "cedro-formal",
    name: "Cedro Formal",
    brand: "Oficina Central",
    family: "amadeirado aromático",
    segments: ["designer"],
    concentrations: ["eau de parfum"],
    topNotes: ["pimenta rosa", "bergamota"],
    heartNotes: ["cipreste", "lavanda"],
    baseNotes: ["cedro", "vetiver", "patchouli"],
    accords: [
      { id: "amadeirado", weight: 0.94 },
      { id: "aromático", weight: 0.76 },
      { id: "especiado fresco", weight: 0.55 },
    ],
    occasions: [
      { id: "formal", weight: 0.94 },
      { id: "escritório", weight: 0.86 },
      { id: "encontro", weight: 0.62 },
    ],
    formality: 0.93,
    performance: {
      longevity: { minimumHours: 7, maximumHours: 10, confidence: "high", sampleSize: 150 },
      projection: metric(0.58, "high", 150),
      sillage: metric(0.55, "high", 142),
    },
    climate: {
      idealTemperatureMinC: 12,
      idealTemperatureMaxC: 28,
      idealHumidity: 0.48,
      indoorFit: 0.82,
      outdoorFit: 0.78,
    },
    priceTier: 3,
    dataConfidence: "high",
    evidence: [evidence("curadoria")],
  },
  {
    id: "pomar-solar",
    name: "Pomar Solar",
    brand: "Quinta Clara",
    family: "frutado cítrico",
    segments: ["brasileiro", "acessível"],
    concentrations: ["eau de cologne"],
    topNotes: ["laranja", "pera"],
    heartNotes: ["flor de laranjeira", "chá branco"],
    baseNotes: ["almíscar", "madeiras claras"],
    accords: [
      { id: "frutado", weight: 0.9 },
      { id: "cítrico", weight: 0.82 },
      { id: "fresco", weight: 0.78 },
    ],
    occasions: [
      { id: "casual", weight: 0.95 },
      { id: "escritório", weight: 0.8 },
      { id: "esporte", weight: 0.64 },
    ],
    formality: 0.3,
    performance: {
      longevity: { minimumHours: 2, maximumHours: 4, confidence: "low", sampleSize: 12 },
      projection: metric(0.28, "low", 12),
      sillage: metric(0.25, "low", 10),
    },
    climate: {
      idealTemperatureMinC: 22,
      idealTemperatureMaxC: 40,
      idealHumidity: 0.72,
      indoorFit: 0.9,
      outdoorFit: 0.78,
    },
    priceTier: 1,
    dataConfidence: "low",
    evidence: [evidence("curadoria", "low", 12)],
  },
];
